### ISSUE TITLE
Todo list / ideas

### ISSUE THREAD

**Issue by kubawolanin** [kubawolanin/drum-tuner#1]
- [ ] Follow-up questions
- [ ] "The `${drumsize}` `${drumType}` sounds best in `${notes}.join(' or ')`"
- [ ] "Badum tshhh!" at the end of conversation
- [ ] More drum tuning tips
- [ ] Pick an option
- [ ] Prefilled options to choose (if device `hasAvailableSurfaceCapabilities()`)
